import type { AppManifest } from "@corely/contracts";

export const restaurantAppManifest: AppManifest = {
  appId: "restaurant",
  name: "Restaurant",
  tier: 2,
  version: "1.0.0",
  description: "Restaurant floor, kitchen queue, modifiers, and operator copilot",
  dependencies: [],
  allowedSurfaces: ["platform", "pos"],
  capabilities: [],
  permissions: [],
  menu: [
    {
      id: "restaurant-floor-plan",
      scope: "web",
      section: "restaurant",
      labelKey: "nav.restaurant.floorPlan",
      defaultLabel: "Floor Plan",
      route: "/restaurant/floor-plan",
      icon: "Map",
      order: 10,
    },
    {
      id: "restaurant-copilot",
      scope: "web",
      section: "restaurant",
      labelKey: "nav.restaurant.copilot",
      defaultLabel: "Restaurant Copilot",
      route: "/restaurant/copilot",
      icon: "Sparkles",
      order: 11,
    },
    {
      id: "restaurant-kitchen-queue",
      scope: "web",
      section: "restaurant",
      labelKey: "nav.restaurant.kitchenQueue",
      defaultLabel: "Kitchen Queue",
      route: "/restaurant/kitchen-queue",
      icon: "ChefHat",
      order: 12,
    },
    {
      id: "restaurant-kitchen-stations",
      scope: "web",
      section: "restaurant",
      labelKey: "nav.restaurant.kitchenStations",
      defaultLabel: "Kitchen Stations",
      route: "/restaurant/kitchen-stations",
      icon: "UtensilsCrossed",
      order: 13,
    },
    {
      id: "restaurant-modifier-groups",
      scope: "web",
      section: "restaurant",
      labelKey: "nav.restaurant.modifierGroups",
      defaultLabel: "Modifier Groups",
      route: "/restaurant/modifier-groups",
      icon: "ListFilter",
      order: 14,
    },
  ],
};
