import type { AppManifest } from "@corely/contracts";

export const taxAppManifest: AppManifest = {
  appId: "tax",
  name: "Tax",
  tier: 2,
  version: "2.0.0",
  description: "Tax Center, Filings, and Compliance",
  dependencies: [],
  capabilities: [],
  permissions: [],
  menu: [
    {
      id: "tax-center",
      scope: "web",
      section: "tax",
      labelKey: "nav.tax.overview",
      defaultLabel: "Overview",
      route: "/tax",
      icon: "LayoutDashboard",
      order: 10,
      exact: true,
    },
    {
      id: "tax-filings",
      scope: "web",
      section: "tax",
      labelKey: "nav.tax.filings",
      defaultLabel: "Filings",
      route: "/tax/filings",
      icon: "Files",
      order: 20,
    },
    {
      id: "tax-payments",
      scope: "web",
      section: "tax",
      labelKey: "nav.tax.payments",
      defaultLabel: "Payments",
      route: "/tax/payments",
      icon: "CreditCard",
      order: 30,
    },
    {
      id: "tax-documents",
      scope: "web",
      section: "tax",
      labelKey: "nav.tax.documents",
      defaultLabel: "Documents",
      route: "/tax/documents",
      icon: "FileText",
      order: 40,
    },
    {
      id: "tax-settings",
      scope: "web",
      section: "tax",
      labelKey: "nav.tax.settings",
      defaultLabel: "Settings",
      route: "/tax/settings",
      icon: "Settings",
      order: 50,
    },
  ],
};
