import type {
  ClassAttendanceEntity,
  ClassBillingInvoiceLinkEntity,
  ClassEnrollmentBillingPlanEntity,
  ClassEnrollmentEntity,
  ClassGroupEntity,
  ClassGroupInstructorEntity,
  ClassGroupResourceEntity,
  ClassMilestoneCompletionEntity,
  ClassMilestoneEntity,
  ClassMonthlyBillingRunEntity,
  ClassProgramEntity,
  ClassProgramMilestoneTemplateEntity,
  ClassProgramSessionTemplateEntity,
  ClassSessionEntity,
} from "../../domain/entities/classes.entities";

export const toClassGroup = (row: any): ClassGroupEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  name: row.name,
  subject: row.subject,
  level: row.level,
  defaultPricePerSession: row.defaultPricePerSession,
  currency: row.currency,
  schedulePattern: row.schedulePattern ?? null,
  status: row.status,
  kind: row.kind,
  lifecycle: row.lifecycle,
  startAt: row.startAt ?? null,
  endAt: row.endAt ?? null,
  timezone: row.timezone ?? "UTC",
  capacity: row.capacity ?? null,
  waitlistEnabled: row.waitlistEnabled ?? false,
  deliveryMode: row.deliveryMode ?? "ONLINE",
  communityUrl: row.communityUrl ?? null,
  programId: row.programId ?? null,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toClassGroupInstructor = (row: any): ClassGroupInstructorEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  classGroupId: row.classGroupId,
  partyId: row.partyId,
  role: row.role,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toProgram = (row: any): ClassProgramEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  title: row.title,
  description: row.description ?? null,
  levelTag: row.levelTag ?? null,
  expectedSessionsCount: row.expectedSessionsCount ?? null,
  defaultTimezone: row.defaultTimezone ?? null,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toProgramSessionTemplate = (row: any): ClassProgramSessionTemplateEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  programId: row.programId,
  index: row.index,
  title: row.title ?? null,
  defaultDurationMin: row.defaultDurationMin ?? null,
  type: row.type,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toProgramMilestoneTemplate = (row: any): ClassProgramMilestoneTemplateEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  programId: row.programId,
  title: row.title,
  type: row.type,
  required: row.required,
  index: row.index,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toClassSession = (row: any): ClassSessionEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  classGroupId: row.classGroupId,
  startsAt: row.startsAt,
  endsAt: row.endsAt ?? null,
  topic: row.topic ?? null,
  notes: row.notes ?? null,
  status: row.status,
  type: row.type ?? "LECTURE",
  meetingProvider: row.meetingProvider ?? null,
  meetingJoinUrl: row.meetingJoinUrl ?? null,
  meetingExternalId: row.meetingExternalId ?? null,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toClassEnrollment = (row: any): ClassEnrollmentEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  classGroupId: row.classGroupId,
  studentClientId: row.studentClientId,
  payerClientId: row.payerClientId,
  payerPartyId: row.payerPartyId ?? null,
  status: row.status ?? "ENROLLED",
  seatType: row.seatType ?? "LEARNER",
  source: row.source ?? "ADMIN",
  startDate: row.startDate ?? null,
  endDate: row.endDate ?? null,
  isActive: row.isActive,
  priceOverridePerSession: row.priceOverridePerSession ?? null,
  priceCents: row.priceCents ?? null,
  currency: row.currency ?? null,
  discountCents: row.discountCents ?? null,
  discountLabel: row.discountLabel ?? null,
  placementLevel: row.placementLevel ?? null,
  placementGoal: row.placementGoal ?? null,
  placementNote: row.placementNote ?? null,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toEnrollmentBillingPlan = (row: any): ClassEnrollmentBillingPlanEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  enrollmentId: row.enrollmentId,
  type: row.type,
  scheduleJson: (row.scheduleJson ?? {}) as Record<string, unknown>,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toClassAttendance = (row: any): ClassAttendanceEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  sessionId: row.sessionId,
  enrollmentId: row.enrollmentId,
  status: row.status,
  billable: row.billable,
  note: row.note ?? null,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toBillingRun = (row: any): ClassMonthlyBillingRunEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  month: row.month,
  billingMonthStrategy: row.billingMonthStrategy,
  billingBasis: row.billingBasis,
  billingSnapshot: row.billingSnapshot ?? null,
  status: row.status,
  runId: row.runId,
  generatedAt: row.generatedAt ?? null,
  createdByUserId: row.createdByUserId,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toBillingInvoiceLink = (row: any): ClassBillingInvoiceLinkEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  billingRunId: row.billingRunId ?? null,
  enrollmentId: row.enrollmentId ?? null,
  payerClientId: row.payerClientId,
  classGroupId: row.classGroupId ?? null,
  invoiceId: row.invoiceId,
  idempotencyKey: row.idempotencyKey,
  purpose: row.purpose ?? "MONTHLY_RUN",
  createdAt: row.createdAt,
});

export const toMilestone = (row: any): ClassMilestoneEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  classGroupId: row.classGroupId,
  programMilestoneTemplateId: row.programMilestoneTemplateId ?? null,
  title: row.title,
  type: row.type,
  dueAt: row.dueAt ?? null,
  required: row.required,
  index: row.index ?? null,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toMilestoneCompletion = (row: any): ClassMilestoneCompletionEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  milestoneId: row.milestoneId,
  enrollmentId: row.enrollmentId,
  status: row.status,
  score: row.score ?? null,
  feedback: row.feedback ?? null,
  gradedByPartyId: row.gradedByPartyId ?? null,
  gradedAt: row.gradedAt ?? null,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

export const toClassGroupResource = (row: any): ClassGroupResourceEntity => ({
  id: row.id,
  tenantId: row.tenantId,
  workspaceId: row.workspaceId,
  classGroupId: row.classGroupId,
  type: row.type,
  title: row.title,
  documentId: row.documentId ?? null,
  url: row.url ?? null,
  visibility: row.visibility,
  sortOrder: row.sortOrder,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});
