import type { AppManifest } from "@corely/contracts";

export const classesAppManifest: AppManifest = {
  appId: "classes",
  name: "Classes",
  tier: 2,
  version: "1.0.0",
  description: "Manage tutoring class groups, sessions, attendance, and billing",
  dependencies: ["invoices", "crm"],
  capabilities: [],
  permissions: [
    "classes.read",
    "classes.write",
    "classes.billing",
    "classes.cohort.manage",
    "classes.cohort.team.manage",
    "classes.cohort.billing.manage",
    "classes.cohort.outcomes.manage",
    "classes.cohort.resources.manage",
    "classes.session.manage",
    "classes.enrollment.manage",
    "classes.programs.view",
    "classes.programs.manage",
    "classes.teacher.dashboard.view",
  ],
  menu: [
    {
      id: "teacher-dashboard",
      scope: "web",
      section: "education",
      labelKey: "nav.teacherDashboard",
      defaultLabel: "Teacher Dashboard",
      route: "/dashboard/teacher",
      icon: "LayoutDashboard",
      order: 10,
      requiresPermissions: ["classes.read"],
    },
    {
      id: "students",
      scope: "web",
      section: "education",
      labelKey: "nav.students",
      defaultLabel: "Students",
      route: "/students",
      icon: "User",
      order: 35,
      requiresPermissions: ["party.customers.read"],
      requiresApps: ["parties"],
    },
    {
      id: "classes-programs",
      scope: "web",
      section: "education",
      labelKey: "nav.programs",
      defaultLabel: "Programs",
      route: "/programs",
      icon: "BookOpen",
      order: 39,
      requiresPermissions: ["classes.programs.view"],
    },
    {
      id: "classes-groups",
      scope: "web",
      section: "education",
      labelKey: "nav.classes",
      defaultLabel: "Classes",
      route: "/classes/cohorts",
      icon: "Users",
      order: 40,
      requiresPermissions: ["classes.read"],
    },
    {
      id: "classes-sessions",
      scope: "web",
      section: "education",
      labelKey: "nav.classSessions",
      defaultLabel: "Sessions",
      route: "/sessions",
      icon: "Calendar",
      order: 41,
      requiresPermissions: ["classes.read"],
    },
    {
      id: "classes-billing",
      scope: "web",
      section: "education",
      labelKey: "nav.classBilling",
      defaultLabel: "Class billing",
      route: "/billing",
      icon: "CreditCard",
      order: 42,
      requiresPermissions: ["classes.billing"],
    },
  ],
};
