/**
 * Centralized test selectors to avoid brittle CSS selectors
 * All selectors should use data-testid attributes
 */

export const selectors = {
  auth: {
    loginEmailInput: 'input[data-testid="login-email"]',
    loginPasswordInput: 'input[data-testid="login-password"]',
    loginSubmitButton: 'button[data-testid="login-submit"]',
    signupEmailInput: 'input[id="email"]',
    signupPasswordInput: 'input[id="password"]',
    signupNameInput: 'input[id="userName"]',
    signupWorkspaceInput: 'input[id="tenantName"]',
    signupSubmitButton: 'button[type="submit"]',
    logoutButton: 'button[data-testid="logout"]',
    userMenu: 'div[data-testid="user-menu"]',
    userMenuButton: 'button[data-testid="user-menu-trigger"]',
  },

  navigation: {
    sidebarNav: 'nav[data-testid="sidebar-nav"]',
    expensesNavLink: 'a[data-testid="nav-expenses"]',
    invoicesNavLink: 'a[data-testid="nav-invoices"]',
    assistantNavLink: 'a[data-testid="nav-assistant"]',
    settingsNavLink: 'a[data-testid="nav-settings"]',
  },

  dashboard: {
    pageTitle: 'h1[data-testid="dashboard-title"]',
    expenseCard: 'div[data-testid="expense-summary-card"]',
    invoiceCard: 'div[data-testid="invoice-summary-card"]',
  },

  expenses: {
    listContainer: 'div[data-testid="expenses-list"]',
    expenseRow: 'tr[data-testid^="expense-row-"]',
    createButton: 'button[data-testid="create-expense-button"]',
    expenseForm: 'form[data-testid="expense-form"]',
    amountInput: 'input[data-testid="expense-amount"]',
    descriptionInput: 'textarea[data-testid="expense-description"]',
    categorySelect: 'select[data-testid="expense-category"]',
    submitButton: 'button[data-testid="expense-submit"]',
    successMessage: 'div[data-testid="expense-success"]',
  },

  invoices: {
    listContainer: 'div[data-testid="invoices-list"]',
    invoiceRow: 'tr[data-testid^="invoice-row-"]',
    createButton: 'button[data-testid="create-invoice-button"]',
    invoiceForm: 'form[data-testid="invoice-form"]',
    customerSelect: '[data-testid="invoice-customer-select"]',
    customerOption: (id: string) => `[data-testid="invoice-customer-option-${id}"]`,
    invoiceNumberInput: 'input[data-testid="invoice-number-input"]',
    lineDescriptionInput: (index = 0) => `input[data-testid="invoice-line-description-${index}"]`,
    lineQtyInput: (index = 0) => `input[data-testid="invoice-line-qty-${index}"]`,
    lineRateInput: (index = 0) => `input[data-testid="invoice-line-rate-${index}"]`,
    submitButton: 'button[data-testid="submit-invoice-button"]',
    statusChip: 'span[data-testid^="invoice-status-"]',
    issueButton: 'button[data-testid="issue-invoice"]',
    draftBadge: 'span[data-testid="invoice-status-draft"]',
    issuedBadge: 'span[data-testid="invoice-status-issued"]',
  },

  assistant: {
    chatContainer: 'div[data-testid="assistant-chat"]',
    messageList: 'div[data-testid="assistant-messages"]',
    inputField: 'input[data-testid="assistant-input"]',
    submitButton: 'button[data-testid="assistant-submit"]',
    toolCard: 'div[data-testid^="assistant-tool-"]',
    confirmButton: 'button[data-testid="assistant-confirm"]',
    addExpenseSuccess: 'div[data-testid="assistant-add-expense-success"]',
    toolcardAccept: 'button[data-testid^="confirm-"]',
    toolcardDismiss: 'button[data-testid^="cancel-"]',
  },

  crm: {
    dealsPage: 'div[data-testid="crm-deals-page"]',
    dealsHeader: 'h1[data-testid="crm-deals-header"]',
    dealsCreate: 'button[data-testid="crm-deals-create"]',
    dealsList: 'div[data-testid="crm-deals-list"]',
    dealsRow: 'div[data-testid^="crm-deals-row-"]',
    leadPage: 'div[data-testid="crm-leads-page"]',
    leadsCreate: 'button[data-testid="crm-leads-create"]',
    leadsList: 'div[data-testid="crm-leads-list"]',
    leadsRow: 'div[data-testid^="crm-leads-row-"]',
    leadForm: 'form[data-testid="crm-lead-form"]',
    leadSave: 'button[data-testid="crm-lead-save"]',
    leadFirstName: 'input[data-testid="crm-lead-first-name"]',
    leadLastName: 'input[data-testid="crm-lead-last-name"]',
    leadCompanyName: 'input[data-testid="crm-lead-company-name"]',
    leadEmail: 'input[data-testid="crm-lead-email"]',
    leadPhone: 'input[data-testid="crm-lead-phone"]',
    leadNotes: 'textarea[data-testid="crm-lead-notes"]',
    leadConvert: 'button[data-testid="crm-lead-convert"]',
    leadStatus: '[data-testid="crm-lead-status"]',
    dealForm: 'form[data-testid="deal-form"]',
    dealSubmit: 'button[data-testid="submit-deal-button"]',
    dealTitle: 'input[data-testid="crm-deal-title"]',
    dealPartyId: 'input[data-testid="crm-deal-party-id"]',
    dealAmount: 'input[data-testid="crm-deal-amount"]',
    dealProbability: 'input[data-testid="crm-deal-probability"]',
    dealNotes: 'textarea[data-testid="crm-deal-notes"]',
    dealDetailPage: 'div[data-testid="crm-deal-detail-page"]',
    dealStageSelect: 'button[data-testid="crm-deal-stage-select"]',
    dealMarkWon: 'button[data-testid="crm-deal-mark-won"]',
    dealMarkLost: 'button[data-testid="crm-deal-mark-lost"]',
    dealQuickNoteSubject: 'input[data-testid="crm-deal-quick-note-subject"]',
    dealQuickNoteAdd: 'button[data-testid="crm-deal-quick-note-add"]',
    activityComposer: 'div[data-testid="crm-activity-composer"]',
    activityAdd: 'button[data-testid="crm-activity-add"]',
    activitySubject: 'input[data-testid="crm-activity-subject"]',
    activityBody: 'textarea[data-testid="crm-activity-body"]',
    activityType: 'button[data-testid="crm-activity-type"]',
    activityOutcome: 'button[data-testid="crm-activity-outcome"]',
    timeline: 'div[data-testid="crm-timeline"]',
    timelineItem: 'div[data-testid^="crm-timeline-item-"]',
    channelOpenEmail: 'button[data-testid="crm-channel-open-email"]',
    channelComposer: 'div[data-testid="crm-channel-composer"]',
    channelMessage: 'textarea[data-testid="crm-channel-message"]',
    channelOpenLink: 'button[data-testid="crm-channel-open-link"]',
    channelLog: 'button[data-testid="crm-channel-log"]',
    // Accounts
    accountsList: 'div[data-testid="crm-accounts-list"]',
    accountsCreate: 'button[data-testid="crm-accounts-create"]',
    accountSave: 'button[data-testid="crm-account-save"]',
    accountName: 'input[data-testid="crm-account-name"]',
    accountDetailName: '[data-testid="crm-account-detail-name"]',
    accountEmail: '[data-testid="crm-account-email"]',
    accountPhone: '[data-testid="crm-account-phone"]',
    accountStatus: '[data-testid="crm-account-status"]',
    accountType: '[data-testid="crm-account-type"]',
    accountOwner: '[data-testid="crm-account-owner"]',
    accountDetail: 'div[data-testid="crm-account-detail"]',
    accountEdit: 'button[data-testid="crm-account-edit"]',
    accountSearch: 'input[data-testid="crm-accounts-search"]',
    dealLostConfirm: 'button[data-testid="crm-deal-lost-confirm"]',
    sequencesPage: 'div[data-testid="crm-sequences-page"]',
    sequencesCreate: 'button[data-testid="crm-sequences-create"]',
    sequenceForm: 'form[data-testid="crm-sequence-form"]',
    sequenceName: 'input[data-testid="crm-sequence-name"]',
    sequenceDescription: 'input[data-testid="crm-sequence-description"]',
    sequenceStepType: 'select[data-testid="crm-sequence-step-type"]',
    sequenceDayDelay: 'input[data-testid="crm-sequence-day-delay"]',
    sequenceStepSubject: 'input[data-testid="crm-sequence-step-subject"]',
    sequenceStepBody: 'textarea[data-testid="crm-sequence-step-body"]',
    sequenceSave: 'button[data-testid="crm-sequence-save"]',
    sequencesList: 'div[data-testid="crm-sequences-list"]',
    sequenceRow: 'div[data-testid^="crm-sequence-row-"]',
    contactsPage: 'div[data-testid="crm-contacts-page"]',
    contactsCreate: 'button[data-testid="crm-contacts-create"]',
    contactsList: 'div[data-testid="crm-contacts-list"]',
    contactRow: 'div[data-testid^="crm-contact-row-"]',
    contactForm: 'form[data-testid="crm-contact-form"]',
    contactName: 'input[data-testid="crm-contact-name"]',
    contactEmail: 'input[data-testid="crm-contact-email"]',
    contactPhone: 'input[data-testid="crm-contact-phone"]',
    contactSave: 'button[data-testid="crm-contact-save"]',
    contactDetail: 'div[data-testid="crm-contact-detail"]',
    contactDetailName: '[data-testid="crm-contact-detail-name"]',
    contactEdit: 'button[data-testid="crm-contact-edit"]',
  },

  common: {
    loader: 'div[data-testid="loader"]',
    errorMessage: 'div[data-testid="error-message"]',
    successMessage: 'div[data-testid="success-message"]',
  },

  workspace: {
    switcherTrigger: 'button[data-testid="workspace-switcher-trigger"]',
    switcherMenu: 'div[data-testid="workspace-switcher-menu"]',
    option: (id: string) => `div[data-testid="workspace-option-${id}"]`,
    onboardingName: 'input[data-testid="onboarding-name"]',
    onboardingLegalName: 'input[data-testid="onboarding-legal-name"]',
    onboardingAddress: 'input[data-testid="onboarding-address-line1"]',
    onboardingCity: 'input[data-testid="onboarding-city"]',
    onboardingPostal: 'input[data-testid="onboarding-postal"]',
    onboardingNext: 'button[data-testid="onboarding-next"]',
    onboardingSubmit: 'button[data-testid="onboarding-submit"]',
    createShortcut: 'button[data-testid="workspace-create-shortcut"]',
  },

  customers: {
    listContainer: 'div[data-testid="customers-list"]',
    createButton: 'button[data-testid="add-customer-button"]',
    customerForm: 'form[data-testid="customer-form"]',
    displayNameInput: 'input[data-testid="customer-displayName-input"]',
    emailInput: 'input[data-testid="customer-email-input"]',
    phoneInput: 'input[data-testid="customer-phone-input"]',
    vatIdInput: 'input[data-testid="customer-vatId-input"]',
    addressLine1Input: 'input[data-testid="customer-address-line1-input"]',
    addressLine2Input: 'input[data-testid="customer-address-line2-input"]',
    addressCityInput: 'input[data-testid="customer-address-city-input"]',
    addressPostalCodeInput: 'input[data-testid="customer-address-postalCode-input"]',
    addressCountryInput: 'input[data-testid="customer-address-country-input"]',
    notesInput: 'textarea[data-testid="customer-notes-input"]',
    submitButton: 'button[data-testid="submit-customer-button"]',
  },
};
