/**
 * Centralized test selectors to avoid brittle CSS selectors
 * All selectors should use data-testid attributes
 */

export const selectors = {
  auth: {
    loginEmailInput: 'input[data-testid="login-email"]',
    loginPasswordInput: 'input[data-testid="login-password"]',
    loginSubmitButton: 'button[data-testid="login-submit"]',
    signupEmailInput: 'input[id="email"]',
    signupPasswordInput: 'input[id="password"]',
    signupNameInput: 'input[id="userName"]',
    signupWorkspaceInput: 'input[id="tenantName"]',
    signupSubmitButton: 'button[type="submit"]',
    logoutButton: 'button[data-testid="logout"]',
    userMenu: 'div[data-testid="user-menu"]',
    userMenuButton: 'button[data-testid="user-menu-trigger"]',
  },

  navigation: {
    sidebarNav: 'nav[data-testid="sidebar-nav"]',
    expensesNavLink: 'nav[data-testid="sidebar-nav"] a[data-testid="nav-expenses"]',
    invoicesNavLink: 'nav[data-testid="sidebar-nav"] a[data-testid="nav-invoices"]',
    assistantNavLink: 'nav[data-testid="sidebar-nav"] a[data-testid="nav-assistant"]',
    settingsNavLink: 'nav[data-testid="sidebar-nav"] a[data-testid="nav-settings"]',
    classesProgramsNavLink: 'nav[data-testid="sidebar-nav"] a[data-testid="nav-classes-programs"]',
    classesGroupsNavLink: 'nav[data-testid="sidebar-nav"] a[data-testid="nav-classes-groups"]',
    teacherDashboardNavLink:
      'nav[data-testid="sidebar-nav"] a[data-testid="nav-teacher-dashboard"]',
  },

  dashboard: {
    pageTitle: 'h1[data-testid="dashboard-title"]',
    expenseCard: 'div[data-testid="expense-summary-card"]',
    invoiceCard: 'div[data-testid="invoice-summary-card"]',
  },

  expenses: {
    listContainer: 'div[data-testid="expenses-list"]',
    expenseRow: 'tr[data-testid^="expense-row-"]',
    createButton: 'button[data-testid="create-expense-button"]',
    expenseForm: 'form[data-testid="expense-form"]',
    amountInput: 'input[data-testid="expense-amount"]',
    descriptionInput: 'textarea[data-testid="expense-description"]',
    categorySelect: 'select[data-testid="expense-category"]',
    submitButton: 'button[data-testid="expense-submit"]',
    successMessage: 'div[data-testid="expense-success"]',
  },

  invoices: {
    listContainer: 'div[data-testid="invoices-list"]',
    invoiceRow: 'tr[data-testid^="invoice-row-"]',
    createButton: 'button[data-testid="create-invoice-button"]',
    invoiceForm: 'form[data-testid="invoice-form"]',
    customerSelect: '[data-testid="invoice-customer-select"]',
    customerOption: (id: string) => `[data-testid="invoice-customer-option-${id}"]`,
    invoiceNumberInput: 'input[data-testid="invoice-number-input"]',
    lineDescriptionInput: (index = 0) => `input[data-testid="invoice-line-description-${index}"]`,
    lineQtyInput: (index = 0) => `input[data-testid="invoice-line-qty-${index}"]`,
    lineRateInput: (index = 0) => `input[data-testid="invoice-line-rate-${index}"]`,
    submitButton: 'button[data-testid="submit-invoice-button"]',
    statusChip: 'span[data-testid^="invoice-status-"]',
    issueButton: 'button[data-testid="issue-invoice"]',
    draftBadge: 'span[data-testid="invoice-status-draft"]',
    issuedBadge: 'span[data-testid="invoice-status-issued"]',
  },

  assistant: {
    chatContainer: 'div[data-testid="assistant-chat"]',
    messageList: 'div[data-testid="assistant-messages"]',
    inputField: 'input[data-testid="assistant-input"]',
    submitButton: 'button[data-testid="assistant-submit"]',
    toolCard: 'div[data-testid^="assistant-tool-"]',
    confirmButton: 'button[data-testid="assistant-confirm"]',
    addExpenseSuccess: 'div[data-testid="assistant-add-expense-success"]',
    toolcardAccept: 'button[data-testid^="confirm-"]',
    toolcardDismiss: 'button[data-testid^="cancel-"]',
  },

  crm: {
    dealsPage: 'div[data-testid="crm-deals-page"]',
    dealsHeader: 'h1[data-testid="crm-deals-header"]',
    dealsCreate: 'button[data-testid="crm-deals-create"]',
    dealsList: 'div[data-testid="crm-deals-list"]',
    dealsRow: 'div[data-testid^="crm-deals-row-"]',
    leadPage: 'div[data-testid="crm-leads-page"]',
    leadsCreate: 'button[data-testid="crm-leads-create"]',
    leadsList: 'div[data-testid="crm-leads-list"]',
    leadsRow: 'div[data-testid^="crm-leads-row-"]',
    leadForm: 'form[data-testid="crm-lead-form"]',
    leadSave: 'button[data-testid="crm-lead-save"]',
    leadFirstName: 'input[data-testid="crm-lead-first-name"]',
    leadLastName: 'input[data-testid="crm-lead-last-name"]',
    leadCompanyName: 'input[data-testid="crm-lead-company-name"]',
    leadEmail: 'input[data-testid="crm-lead-email"]',
    leadPhone: 'input[data-testid="crm-lead-phone"]',
    leadNotes: 'textarea[data-testid="crm-lead-notes"]',
    leadConvert: 'button[data-testid="crm-lead-convert"]',
    leadStatus: '[data-testid="crm-lead-status"]',
    dealForm: 'form[data-testid="deal-form"]',
    dealSubmit: 'button[data-testid="submit-deal-button"]',
    dealTitle: 'input[data-testid="crm-deal-title"]',
    dealPartyId: '[data-testid="crm-deal-party-id"]',
    dealAmount: 'input[data-testid="crm-deal-amount"]',
    dealProbability: 'input[data-testid="crm-deal-probability"]',
    dealNotes: 'textarea[data-testid="crm-deal-notes"]',
    dealDetailPage: 'div[data-testid="crm-deal-detail-page"]',
    dealAiInsightsCard: 'div[data-testid="crm-deal-ai-insights"]',
    dealStageSelect: 'button[data-testid="crm-deal-stage-select"]',
    dealMarkWon: 'button[data-testid="crm-deal-mark-won"]',
    dealMarkLost: 'button[data-testid="crm-deal-mark-lost"]',
    dealQuickNoteSubject: 'input[data-testid="crm-deal-quick-note-subject"]',
    dealQuickNoteAdd: 'button[data-testid="crm-deal-quick-note-add"]',
    activityComposer: 'div[data-testid="crm-activity-composer"]',
    activityAdd: 'button[data-testid="crm-activity-add"]',
    activitySubject: 'input[data-testid="crm-activity-subject"]',
    activityBody: 'textarea[data-testid="crm-activity-body"]',
    newActivitySubject: 'input[data-testid="crm-new-activity-subject"]',
    activityType: 'button[data-testid="crm-activity-type"]',
    activityOutcome: 'button[data-testid="crm-activity-outcome"]',
    timeline: 'div[data-testid="crm-timeline"]',
    timelineItem: 'div[data-testid^="crm-timeline-item-"]',
    channelOpenEmail: 'button[data-testid="crm-channel-open-email"]',
    channelComposer: 'div[data-testid="crm-channel-composer"]',
    channelMessage: 'textarea[data-testid="crm-channel-message"]',
    channelOpenLink: 'button[data-testid="crm-channel-open-link"]',
    channelLog: 'button[data-testid="crm-channel-log"]',
    // Accounts
    accountsList: 'div[data-testid="crm-accounts-list"]',
    accountsCreate: 'button[data-testid="crm-accounts-create"]',
    accountSave: 'button[data-testid="crm-account-save"]',
    accountName: 'input[data-testid="crm-account-name"]',
    accountDetailName: '[data-testid="crm-account-detail-name"]',
    accountEmail: '[data-testid="crm-account-email"]',
    accountPhone: '[data-testid="crm-account-phone"]',
    accountStatus: '[data-testid="crm-account-status"]',
    accountType: '[data-testid="crm-account-type"]',
    accountOwner: '[data-testid="crm-account-owner"]',
    accountDetail: 'div[data-testid="crm-account-detail"]',
    accountEdit: 'button[data-testid="crm-account-edit"]',
    accountSearch: 'input[data-testid="crm-accounts-search"]',
    dealLostConfirm: 'button[data-testid="crm-deal-lost-confirm"]',
    activityDescribeInput: 'input[data-testid="crm-activity-describe-input"]',
    activityDescribeParse: 'button[data-testid="crm-activity-describe-parse"]',
    activityDescribeApply: 'button[data-testid="crm-activity-describe-apply"]',
    sequencesPage: 'div[data-testid="crm-sequences-page"]',
    sequencesCreate: 'button[data-testid="crm-sequences-create"]',
    sequenceForm: 'form[data-testid="crm-sequence-form"]',
    sequenceName: 'input[data-testid="crm-sequence-name"]',
    sequenceDescription: 'input[data-testid="crm-sequence-description"]',
    sequenceStepType: 'select[data-testid="crm-sequence-step-type"]',
    sequenceDayDelay: 'input[data-testid="crm-sequence-day-delay"]',
    sequenceStepSubject: 'input[data-testid="crm-sequence-step-subject"]',
    sequenceStepBody: 'textarea[data-testid="crm-sequence-step-body"]',
    sequenceSave: 'button[data-testid="crm-sequence-save"]',
    sequencesList: 'div[data-testid="crm-sequences-list"]',
    sequenceRow: 'div[data-testid^="crm-sequence-row-"]',
    contactsPage: 'div[data-testid="crm-contacts-page"]',
    contactsCreate: 'button[data-testid="crm-contacts-create"]',
    contactsList: 'div[data-testid="crm-contacts-list"]',
    contactRow: 'div[data-testid^="crm-contact-row-"]',
    contactForm: 'form[data-testid="crm-contact-form"]',
    contactName: 'input[data-testid="crm-contact-name"]',
    contactEmail: 'input[data-testid="crm-contact-email"]',
    contactPhone: 'input[data-testid="crm-contact-phone"]',
    contactSave: 'button[data-testid="crm-contact-save"]',
    contactDetail: 'div[data-testid="crm-contact-detail"]',
    contactDetailName: '[data-testid="crm-contact-detail-name"]',
    contactEdit: 'button[data-testid="crm-contact-edit"]',
  },

  common: {
    loader: 'div[data-testid="loader"]',
    errorMessage: 'div[data-testid="error-message"]',
    successMessage: 'div[data-testid="success-message"]',
  },

  workspace: {
    switcherTrigger: 'button[data-testid="workspace-switcher-trigger"]',
    switcherMenu: 'div[data-testid="workspace-switcher-menu"]',
    option: (id: string) => `div[data-testid="workspace-option-${id}"]`,
    onboardingName: 'input[data-testid="onboarding-name"]',
    onboardingLegalName: 'input[data-testid="onboarding-legal-name"]',
    onboardingAddress: 'input[data-testid="onboarding-address-line1"]',
    onboardingCity: 'input[data-testid="onboarding-city"]',
    onboardingPostal: 'input[data-testid="onboarding-postal"]',
    onboardingNext: 'button[data-testid="onboarding-next"]',
    onboardingSubmit: 'button[data-testid="onboarding-submit"]',
    createShortcut: 'button[data-testid="workspace-create-shortcut"]',
  },

  customers: {
    listContainer: 'div[data-testid="customers-list"]',
    createButton: 'button[data-testid="add-customer-button"]',
    customerForm: 'form[data-testid="customer-form"]',
    displayNameInput: 'input[data-testid="customer-displayName-input"]',
    emailInput: 'input[data-testid="customer-email-input"]',
    phoneInput: 'input[data-testid="customer-phone-input"]',
    vatIdInput: 'input[data-testid="customer-vatId-input"]',
    addressLine1Input: 'input[data-testid="customer-address-line1-input"]',
    addressLine2Input: 'input[data-testid="customer-address-line2-input"]',
    addressCityInput: 'input[data-testid="customer-address-city-input"]',
    addressPostalCodeInput: 'input[data-testid="customer-address-postalCode-input"]',
    addressCountryInput: 'input[data-testid="customer-address-country-input"]',
    notesInput: 'textarea[data-testid="customer-notes-input"]',
    submitButton: 'button[data-testid="submit-customer-button"]',
  },

  classes: {
    programsList: '[data-testid="classes-programs-list"]',
    programsNewButton: '[data-testid="classes-programs-new-button"]',
    programRow: (id: string) => `[data-testid="classes-program-row-${id}"]`,
    programDetail: '[data-testid="classes-program-detail-screen"]',
    programTitleInput: '[data-testid="classes-program-title-input"]',
    programLevelTagInput: '[data-testid="classes-program-level-tag-input"]',
    programExpectedSessionsInput: '[data-testid="classes-program-expected-sessions-input"]',
    programTimezoneInput: '[data-testid="classes-program-timezone-input"]',
    programDescriptionInput: '[data-testid="classes-program-description-input"]',
    programSaveButton: '[data-testid="classes-program-save-button"]',
    programAddSessionTemplateButton: '[data-testid="classes-program-add-session-template-button"]',
    programAddMilestoneTemplateButton:
      '[data-testid="classes-program-add-milestone-template-button"]',
    programCreateCohortPanel: '[data-testid="classes-program-create-cohort-panel"]',
    programCreateCohortButton: '[data-testid="classes-program-create-cohort-button"]',
    cohortsList: '[data-testid="classes-cohorts-list"]',
    cohortRow: (id: string) => `[data-testid="classes-cohort-row-${id}"]`,
    cohortDetail: '[data-testid="classes-cohort-detail-screen"]',
    cohortLifecycleBadge: '[data-testid="classes-cohort-lifecycle-badge"]',
    cohortLifecycleNextButton: '[data-testid="classes-cohort-lifecycle-next-button"]',
    cohortTabOverview: '[data-testid="classes-cohort-tab-overview"]',
    cohortTabSessions: '[data-testid="classes-cohort-tab-sessions"]',
    cohortTabLearners: '[data-testid="classes-cohort-tab-learners"]',
    cohortTabBilling: '[data-testid="classes-cohort-tab-billing"]',
    cohortTabOutcomes: '[data-testid="classes-cohort-tab-outcomes"]',
    cohortTabResources: '[data-testid="classes-cohort-tab-resources"]',
    cohortTeamPartyPicker: '[data-testid="classes-cohort-team-party-picker"]',
    cohortTeamPartyOption: (id: string) => `[data-testid="classes-cohort-team-party-option-${id}"]`,
    cohortTeamRoleSelect: '[data-testid="classes-cohort-team-role-select"]',
    cohortTeamAddButton: '[data-testid="classes-cohort-team-add-button"]',
    cohortTeamRole: (role: string) => `[data-testid="classes-cohort-team-role-${role}"]`,
    cohortSessionRow: (id: string) => `[data-testid="classes-cohort-session-row-${id}"]`,
    cohortCreateApplicationStudent: '[data-testid="classes-cohort-application-student-client-id"]',
    cohortCreateApplicationPayer: '[data-testid="classes-cohort-application-payer-client-id"]',
    cohortCreateApplicationPlacementLevel:
      '[data-testid="classes-cohort-application-placement-level"]',
    cohortCreateApplicationPlacementGoal:
      '[data-testid="classes-cohort-application-placement-goal"]',
    cohortCreateApplicationButton: '[data-testid="classes-cohort-application-create-button"]',
    cohortLearnersStatusFilter: (status: string) =>
      `[data-testid="classes-cohort-learners-status-${status}"]`,
    cohortEnrollmentRow: (id: string) => `[data-testid="classes-cohort-enrollment-row-${id}"]`,
    cohortEnrollmentApprove: (id: string) =>
      `[data-testid="classes-cohort-enrollment-approve-${id}"]`,
    cohortBillingPlanTypeSelect: '[data-testid="classes-cohort-billing-plan-type-select"]',
    cohortBillingAmountInput: '[data-testid="classes-cohort-billing-amount-input"]',
    cohortBillingCurrencyInput: '[data-testid="classes-cohort-billing-currency-input"]',
    cohortBillingDueDateInput: '[data-testid="classes-cohort-billing-due-date-input"]',
    cohortBillingSavePlanButton: '[data-testid="classes-cohort-billing-save-plan-button"]',
    cohortBillingGenerateInvoicesButton:
      '[data-testid="classes-cohort-billing-generate-invoices-button"]',
    cohortBillingCurrentPlan: '[data-testid="classes-cohort-billing-current-plan"]',
    cohortMilestoneTitleInput: '[data-testid="classes-cohort-milestone-title-input"]',
    cohortMilestoneAddButton: '[data-testid="classes-cohort-milestone-add-button"]',
    cohortMilestoneRow: (id: string) => `[data-testid="classes-cohort-milestone-row-${id}"]`,
    cohortMilestoneStatus: (id: string) => `[data-testid="classes-cohort-milestone-status-${id}"]`,
    cohortOutcomesPassedCount: '[data-testid="classes-cohort-outcomes-passed-count"]',
    cohortResourceTypeSelect: '[data-testid="classes-cohort-resource-type-select"]',
    cohortResourceVisibilitySelect: '[data-testid="classes-cohort-resource-visibility-select"]',
    cohortResourceTitleInput: '[data-testid="classes-cohort-resource-title-input"]',
    cohortResourceUrlInput: '[data-testid="classes-cohort-resource-url-input"]',
    cohortResourceAddButton: '[data-testid="classes-cohort-resource-add-button"]',
    cohortResourceRow: (id: string) => `[data-testid="classes-cohort-resource-row-${id}"]`,
    cohortResourceUp: (id: string) => `[data-testid="classes-cohort-resource-up-${id}"]`,
    cohortResourceDown: (id: string) => `[data-testid="classes-cohort-resource-down-${id}"]`,
    cohortResourceDelete: (id: string) => `[data-testid="classes-cohort-resource-delete-${id}"]`,
    teacherDashboard: '[data-testid="classes-teacher-dashboard"]',
    teacherDashboardClassFilter: '[data-testid="classes-teacher-dashboard-class-group-filter"]',
    teacherDashboardTodayCard: '[data-testid="classes-teacher-dashboard-card-sessions-today"]',
    teacherDashboardNeedsAttention: '[data-testid="classes-teacher-dashboard-needs-attention"]',
  },
};
