import type { AppManifest } from "@corely/contracts";

export const catalogAppManifest: AppManifest = {
  appId: "catalog",
  name: "Catalog",
  tier: 2,
  version: "1.0.0",
  description: "Manage products, variants, units, and tax profiles",
  dependencies: [],
  allowedSurfaces: ["platform", "pos"],
  capabilities: ["catalog.basic"],
  permissions: ["catalog.read", "catalog.quickwrite", "catalog.write"],
  entitlement: {
    defaultEnabled: true,
  },
  menu: [
    {
      id: "catalog-items",
      scope: "web",
      section: "inventory",
      labelKey: "nav.catalogItems",
      defaultLabel: "Catalog Items",
      route: "/catalog/items",
      icon: "Package",
      order: 5,
      allowedSurfaces: ["platform"],
      requiresCapabilities: ["catalog.basic"],
      requiresPermissions: ["catalog.read"],
    },
    {
      id: "pos-catalog-lookup",
      scope: "web",
      section: "pos",
      labelKey: "nav.pos.catalog",
      defaultLabel: "Catalog",
      route: "/pos/catalog",
      icon: "Package",
      order: 25,
      allowedSurfaces: ["pos"],
      requiresCapabilities: ["catalog.basic"],
      requiresPermissions: ["catalog.read"],
    },
    {
      id: "pos-catalog-quick-add",
      scope: "web",
      section: "pos",
      labelKey: "nav.pos.catalogQuickAdd",
      defaultLabel: "Quick Add Item",
      route: "/pos/catalog/new",
      icon: "Package",
      order: 26,
      allowedSurfaces: ["pos"],
      requiresCapabilities: ["catalog.basic"],
      requiresPermissions: ["catalog.quickwrite"],
    },
  ],
};
