export const posTheme = {
  colors: {
    primary: "#003399",
    primaryHover: "#002C85",
    primaryPressed: "#00246D",
    accent: "#FFCC00",
    white: "#FFFFFF",
    black: "#000000",
    background: "#F3F5FA",
    surface: "#FFFFFF",
    surfaceMuted: "#EEF1F8",
    text: "#111827",
    textMuted: "#556079",
    border: "#D9DEEA",
    danger: "#C0362C",
    warning: "#A86B00",
    success: "#0F8A4B",
    info: "#1C4ED8",
    overlayScrim: "rgba(10, 18, 45, 0.35)",
    overlayDark: "rgba(0, 0, 0, 0.55)",
    statusSuccessSoft: "#DFF5E8",
    statusDangerSoft: "#FDE7E7",
    statusWarningSoft: "#FFF3D6",
    statusInfoSoft: "#E6EEFF",
    syncOnlineBg: "#EAF7F0",
    syncOnlineBorder: "#8BD4A9",
    syncSyncingBg: "#E8EEFF",
    syncSyncingBorder: "#9CB2FF",
    syncAttentionBg: "#FFF4D9",
    syncAttentionBorder: "#FFD874",
    syncOfflineBg: "#FDEDED",
    syncOfflineBorder: "#F5AEAE",
    snackbarWarningBg: "#FFE8A7",
    cartDeleteSoft: "#FCE8E8",
    toggleOnBg: "#9FE2C5",
    toggleOffBg: "#D7E0DB",
    kioskOnlineDot: "#1FA064",
    kioskOfflineDot: "#D13A3A",
    kioskSubtitle: "#E8EEFF",
    kioskDescription: "#DBE6FF",
    bannerErrorBg: "#FEE2E2",
    bannerWarningBg: "#FEF3C7",
    bannerInfoBg: "#DBEAFE",
    bannerErrorText: "#991B1B",
    bannerWarningText: "#92400E",
    bannerInfoText: "#1E40AF",
    bannerErrorBorder: "#FCA5A5",
    bannerWarningBorder: "#FCD34D",
    bannerInfoBorder: "#93C5FD",
    // legacy aliases
    bg: "#F3F5FA",
    primaryMuted: "#E7EEFF",
  },
  typography: {
    title: {
      fontSize: 30,
      fontWeight: "800" as const,
      lineHeight: 36,
    },
    heading: {
      fontSize: 22,
      fontWeight: "800" as const,
      lineHeight: 28,
    },
    subheading: {
      fontSize: 18,
      fontWeight: "700" as const,
      lineHeight: 24,
    },
    body: {
      fontSize: 16,
      fontWeight: "500" as const,
      lineHeight: 22,
    },
    caption: {
      fontSize: 13,
      fontWeight: "500" as const,
      lineHeight: 18,
    },
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  radius: {
    md: 12,
    lg: 16,
    xl: 20,
    pill: 999,
    // legacy
    sm: 12,
  },
  elevation: {
    card: {
      shadowColor: "#0B1A3D",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.08,
      shadowRadius: 14,
      elevation: 3,
    },
    elevated: {
      shadowColor: "#0B1A3D",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.14,
      shadowRadius: 18,
      elevation: 6,
    },
  },
  breakpoints: {
    phoneMax: 719,
    tabletMin: 720,
    wideMin: 1024,
  },
} as const;

export type PosTheme = typeof posTheme;
