import { Injectable } from "@nestjs/common";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { format } from "date-fns";

export type TaxReportPdfModel = {
  title: string;
  tenantName: string;
  periodLabel: string;
  periodStart: Date;
  periodEnd: Date;
  generatedAt: Date;
  items: Array<{ label: string; value: string }>;
  submission?: {
    date: Date;
    reference: string | null;
  };
};

@Injectable()
export class TaxPdfRenderer {
  async render(model: TaxReportPdfModel): Promise<Buffer> {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage();
    const { width, height } = page.getSize();
    const margin = 50;

    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let cursorY = height - margin;

    const drawText = (
      text: string,
      options: { size?: number; font?: any; x?: number; color?: any } = {}
    ) => {
      page.drawText(text, {
        x: options.x ?? margin,
        y: cursorY,
        size: options.size ?? 12,
        font: options.font ?? fontRegular,
        color: options.color ?? rgb(0, 0, 0),
      });
    };

    // Header
    drawText(model.tenantName.toUpperCase(), { size: 10, color: rgb(0.5, 0.5, 0.5) });
    cursorY -= 20;

    drawText(model.title, { size: 24, font: fontBold });
    cursorY -= 30;

    // Period Info
    drawText(`Period: ${model.periodLabel}`, { size: 14, font: fontBold });
    cursorY -= 20;
    drawText(`Date Range: ${format(model.periodStart, "PP")} - ${format(model.periodEnd, "PP")}`);
    cursorY -= 20;

    // Submission Info
    if (model.submission) {
      drawText(`Submitted on: ${format(model.submission.date, "PPpp")}`);
      cursorY -= 15;
      if (model.submission.reference) {
        drawText(`Reference: ${model.submission.reference}`);
        cursorY -= 15;
      }
      cursorY -= 10;
    }

    cursorY -= 20;

    // Draw Divider
    page.drawLine({
      start: { x: margin, y: cursorY },
      end: { x: width - margin, y: cursorY },
      thickness: 1,
      color: rgb(0.8, 0.8, 0.8),
    });
    cursorY -= 30;

    // Items
    for (const item of model.items) {
      drawText(item.label);
      // Draw value right aligned
      const valueWidth = fontBold.widthOfTextAtSize(item.value, 12);
      page.drawText(item.value, {
        x: width - margin - valueWidth,
        y: cursorY,
        size: 12,
        font: fontBold,
      });
      cursorY -= 25;
    }

    // Footer
    const footerText = `Generated by Corely on ${format(model.generatedAt, "PPpp")}`;
    page.drawText(footerText, {
      x: margin,
      y: margin,
      size: 8,
      font: fontRegular,
      color: rgb(0.6, 0.6, 0.6),
    });

    const bytes = await pdfDoc.save();
    return Buffer.from(bytes);
  }
}
