import type {
  PortfolioShowcase,
  PortfolioProfile,
  PortfolioProject,
  PortfolioClient,
  PortfolioService,
  PortfolioTeamMember,
} from "../../domain/portfolio.types";
import type {
  PortfolioShowcase as PortfolioShowcaseDto,
  PortfolioProfile as PortfolioProfileDto,
  PortfolioProject as PortfolioProjectDto,
  PortfolioClient as PortfolioClientDto,
  PortfolioService as PortfolioServiceDto,
  PortfolioTeamMember as PortfolioTeamMemberDto,
} from "@corely/contracts";

export const toPortfolioShowcaseDto = (showcase: PortfolioShowcase): PortfolioShowcaseDto => ({
  id: showcase.id,
  tenantId: showcase.tenantId,
  workspaceId: showcase.workspaceId,
  type: showcase.type,
  name: showcase.name,
  slug: showcase.slug,
  primaryDomain: showcase.primaryDomain ?? null,
  isPublished: showcase.isPublished,
  createdAt: showcase.createdAt.toISOString(),
  updatedAt: showcase.updatedAt.toISOString(),
});

export const toPortfolioProfileDto = (profile: PortfolioProfile): PortfolioProfileDto => ({
  id: profile.id,
  tenantId: profile.tenantId,
  workspaceId: profile.workspaceId,
  showcaseId: profile.showcaseId,
  introLine: profile.introLine ?? null,
  headline: profile.headline ?? null,
  subheadline: profile.subheadline ?? null,
  aboutShort: profile.aboutShort ?? null,
  aboutLong: profile.aboutLong ?? null,
  focusBullets: profile.focusBullets,
  ctaTitle: profile.ctaTitle ?? null,
  ctaText: profile.ctaText ?? null,
  ctaUrl: profile.ctaUrl ?? null,
  techStacks: profile.techStacks,
  socialLinks: profile.socialLinks ?? null,
  homeSections: profile.homeSections,
  isPublished: profile.isPublished,
  createdAt: profile.createdAt.toISOString(),
  updatedAt: profile.updatedAt.toISOString(),
});

export const toPortfolioProjectDto = (project: PortfolioProject): PortfolioProjectDto => ({
  id: project.id,
  tenantId: project.tenantId,
  workspaceId: project.workspaceId,
  showcaseId: project.showcaseId,
  title: project.title,
  slug: project.slug,
  summary: project.summary,
  content: project.content,
  type: project.type,
  status: project.status,
  featured: project.featured,
  sortOrder: project.sortOrder ?? null,
  coverImageUrl: project.coverImageUrl ?? null,
  links: project.links ?? null,
  techStack: project.techStack,
  metrics: project.metrics ?? null,
  createdAt: project.createdAt.toISOString(),
  updatedAt: project.updatedAt.toISOString(),
});

export const toPortfolioClientDto = (client: PortfolioClient): PortfolioClientDto => ({
  id: client.id,
  tenantId: client.tenantId,
  workspaceId: client.workspaceId,
  showcaseId: client.showcaseId,
  name: client.name,
  slug: client.slug,
  clientType: client.clientType,
  locationText: client.locationText,
  websiteUrl: client.websiteUrl ?? null,
  logoImageUrl: client.logoImageUrl ?? null,
  summary: client.summary ?? null,
  testimonialQuote: client.testimonialQuote ?? null,
  testimonialAuthor: client.testimonialAuthor ?? null,
  featured: client.featured,
  sortOrder: client.sortOrder ?? null,
  createdAt: client.createdAt.toISOString(),
  updatedAt: client.updatedAt.toISOString(),
});

export const toPortfolioServiceDto = (service: PortfolioService): PortfolioServiceDto => ({
  id: service.id,
  tenantId: service.tenantId,
  workspaceId: service.workspaceId,
  showcaseId: service.showcaseId,
  name: service.name,
  slug: service.slug,
  shortDescription: service.shortDescription,
  deliverables: service.deliverables,
  startingFromPrice: service.startingFromPrice ?? null,
  ctaText: service.ctaText ?? null,
  ctaUrl: service.ctaUrl ?? null,
  status: service.status,
  sortOrder: service.sortOrder ?? null,
  createdAt: service.createdAt.toISOString(),
  updatedAt: service.updatedAt.toISOString(),
});

export const toPortfolioTeamMemberDto = (member: PortfolioTeamMember): PortfolioTeamMemberDto => ({
  id: member.id,
  tenantId: member.tenantId,
  workspaceId: member.workspaceId,
  showcaseId: member.showcaseId,
  name: member.name,
  roleTitle: member.roleTitle,
  bio: member.bio,
  skills: member.skills,
  photoUrl: member.photoUrl ?? null,
  socialLinks: member.socialLinks ?? null,
  status: member.status,
  sortOrder: member.sortOrder ?? null,
  createdAt: member.createdAt.toISOString(),
  updatedAt: member.updatedAt.toISOString(),
});
