export * from "./tax-profile-repo.port";
export * from "./tax-code-repo.port";
export * from "./tax-rate-repo.port";
export * from "./tax-snapshot-repo.port";
export * from "./vat-report-repo.port";
export * from "./tax-consultant-repo.port";
export * from "./tax-report-repo.port";
export * from "./tax-summary-query.port";
export * from "./vat-period-query.port";
