import type { AppManifest } from "@corely/contracts";

/**
 * CRM App Manifest
 * Defines the CRM module as an installable app
 */
export const crmAppManifest: AppManifest = {
  appId: "crm",
  name: "CRM",
  tier: 2,
  version: "1.0.0",
  description: "Manage deals, activities, and customer relationships",
  dependencies: ["parties"],
  allowedSurfaces: ["platform", "crm"],
  capabilities: ["crm.deals", "crm.activities"],
  permissions: [
    "crm.deals.read",
    "crm.deals.manage",
    "crm.activities.read",
    "crm.activities.manage",
  ],
  menu: [
    {
      id: "crm-dashboard",
      scope: "web",
      section: "crm",
      labelKey: "nav.crmDashboard",
      defaultLabel: "Dashboard",
      route: "/crm",
      icon: "LayoutDashboard",
      order: 30,
      exact: true,
    },
    {
      id: "crm-assistant",
      scope: "web",
      section: "crm",
      labelKey: "nav.assistant",
      defaultLabel: "Assistant",
      route: "/assistant",
      icon: "Sparkles",
      order: 31,
      allowedSurfaces: ["crm"],
    },
    {
      id: "crm-deals",
      scope: "web",
      section: "crm",
      labelKey: "nav.crmDeals",
      defaultLabel: "Deals",
      route: "/crm/deals",
      icon: "FolderKanban",
      order: 32,
      requiresPermissions: ["crm.deals.read"],
    },
    {
      id: "crm-leads",
      scope: "web",
      section: "crm",
      labelKey: "nav.crmLeads",
      defaultLabel: "Leads",
      route: "/crm/leads",
      icon: "Users",
      order: 33,
    },
    {
      id: "crm-activities",
      scope: "web",
      section: "crm",
      labelKey: "nav.crmActivities",
      defaultLabel: "Activities",
      route: "/crm/activities",
      icon: "ClipboardList",
      order: 34,
      requiresPermissions: ["crm.activities.read"],
    },
    {
      id: "crm-sequences",
      scope: "web",
      section: "crm",
      labelKey: "nav.crmSequences",
      defaultLabel: "Sequences",
      route: "/crm/sequences",
      icon: "Zap",
      order: 35,
      // requiresPermissions: ["crm.sequences.read"], // TODO: Add permissions
    },
    {
      id: "crm-email-settings",
      scope: "web",
      section: "crm",
      labelKey: "nav.crmEmailSettings",
      defaultLabel: "Email Settings",
      route: "/crm/settings/email",
      icon: "Mail",
      order: 36,
    },
    {
      id: "crm-templates-settings",
      scope: "web",
      section: "settings",
      labelKey: "nav.crmTemplates",
      defaultLabel: "Templates",
      route: "/settings/engagement/templates",
      icon: "FileText",
      order: 138,
      requiresPermissions: ["crm.deals.manage"],
    },
  ],
};
